/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import logica.Producto;
import logica.Tienda;
import logica.Usuarios;

/**
 *
 * @author adryh
 */
public class AltaProducto extends javax.swing.JFrame {
    BufferedImage bImage =null;
    File seleccionado=new File("");
    int comprobare = 0;
    
   /**
     * Creates new form AltaProducto
     */
    public AltaProducto() {
        initComponents();
        this.setLocationRelativeTo(null);

        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        ImageIcon img = new ImageIcon(s + "\\src\\logos\\logo32px.png");
        this.setIconImage(img.getImage());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCategoría = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCondicion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedPrecio = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonBuscarImagen = new javax.swing.JButton();
        jPanelImagenPre = new javax.swing.JPanel();
        jLabelIcono = new javax.swing.JLabel();
        jButtonVenderFin = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jCheckBoxUrgente = new javax.swing.JCheckBox();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venta de producto");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Título");

        jLabel2.setText("(Máx. 30 caracteres)");

        jTextDescripcion.setColumns(20);
        jTextDescripcion.setLineWrap(true);
        jTextDescripcion.setRows(5);
        jTextDescripcion.setToolTipText("");
        jTextDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextDescripcion);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descrición");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Categoría");

        jComboBoxCategoría.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Elige una categoría------", "Moda y accesorios ", "TV, audio y fotografía", "Móviles y telefonía", "Informática y electrónica ", "Consolas y videojuegos ", "Deporte y ocio", "Hogar y decoración", "Cine, libros y música" }));
        jComboBoxCategoría.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Condición del producto");

        jComboBoxCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Condición del Producto------", "Nuevo ", "Como nuevo", "Bueno", "Aceptable", "Regular", "Estropeado" }));
        jComboBoxCondicion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VENDER UN PRODUCTO");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Precio");

        jFormattedPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedPrecioActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Imagen del producto");

        jButtonBuscarImagen.setText("Buscar Imagen");
        jButtonBuscarImagen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarImagenActionPerformed(evt);
            }
        });

        jPanelImagenPre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/logo128px.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagenPreLayout = new javax.swing.GroupLayout(jPanelImagenPre);
        jPanelImagenPre.setLayout(jPanelImagenPreLayout);
        jPanelImagenPreLayout.setHorizontalGroup(
            jPanelImagenPreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagenPreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelImagenPreLayout.setVerticalGroup(
            jPanelImagenPreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenPreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonVenderFin.setText("Vender");
        jButtonVenderFin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVenderFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderFinActionPerformed(evt);
            }
        });

        jButtonAtras.setText("Atras");
        jButtonAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jCheckBoxUrgente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxUrgente.setText("Venta urgente");
        jCheckBoxUrgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUrgenteActionPerformed(evt);
            }
        });

        jLabel8.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextFieldTitulo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanelImagenPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonBuscarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxCondicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jFormattedPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addGap(74, 74, 74)))))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVenderFin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jCheckBoxUrgente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBoxCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(105, 105, 105))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jCheckBoxUrgente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBuscarImagen, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addComponent(jPanelImagenPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVenderFin, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedPrecioActionPerformed

    private void jButtonBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarImagenActionPerformed

        //crear el objeto jFileChooser
        JFileChooser file = new JFileChooser();

        //Filtro para que solo admita imagenes .jpg o .png
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();

        file.setCurrentDirectory(new File(s + "\\src\\ImagenesProductos"));
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.Images", "jpg", "png");
        file.addChoosableFileFilter(filtro);
        
        //abrir la ventana
        int resultado = file.showSaveDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            seleccionado = file.getSelectedFile();
            String rutaAbsImagen = seleccionado.getAbsolutePath();
            ImageIcon imagen = new ImageIcon(rutaAbsImagen);
            //redimensión para ajustar:
            ImageIcon imgRedim = new ImageIcon(imagen.getImage().getScaledInstance(jLabelIcono.getWidth(), jLabelIcono.getHeight(), 1));
            jLabelIcono.setIcon(imgRedim);
            comprobare=1;            
            
            
        } else if (resultado == JFileChooser.CANCEL_OPTION) {

            JOptionPane.showMessageDialog(rootPane, "Ninguna imagen seleccionada");

        }


    }//GEN-LAST:event_jButtonBuscarImagenActionPerformed

    private void jCheckBoxUrgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUrgenteActionPerformed
        if (jCheckBoxUrgente.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Al marcar un producto como “urgente” pagará 5€ y de esta forma,"
                    + " su producto destacará sobre los demás durante 7 días.  \n"
                    + " ");
        }
    }//GEN-LAST:event_jCheckBoxUrgenteActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonVenderFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderFinActionPerformed

        //proceso de validacion de campos
        String errores = "Los siguientes campos son incorrectos:";
        boolean valido = true;
        String msgUrgente = "";
        //pre-guardado de los textos insertados:

        
        String tituloAlta = jTextFieldTitulo.getText();
        String descripcionAlta = jTextDescripcion.getText();
        String categoriaAlta = jComboBoxCategoría.getSelectedItem().toString();
        String condicionAlta = jComboBoxCondicion.getSelectedItem().toString();
        
        String precioPre = jFormattedPrecio.getText().replace(".","");
        precioPre=precioPre.replace(",", ".");
        Double precioAlta = Double.parseDouble(precioPre);
        
        String fechaAlta = Tienda.fechaActual();
        //Ubicación = vendedor.cp + vendedor.ciudad
        boolean urgente = jCheckBoxUrgente.isSelected();
        
        
        if (comprobare == 0){
            errores += "\nEl producto necesita una imagen";
            valido = false;
        
        }
        if ((tituloAlta.isBlank()||(tituloAlta.length()>30))) {
            errores += "\nEl producto debe tener un título menor de 30 carácteres";
            valido = false;
        }
        if (descripcionAlta.isBlank()) {
            errores += "\nEl producto debe tener una descripción";
            valido = false;
        }
        if (precioAlta < 0) {
            errores += "\nEl producto debe tener un precio superior a 0€";
            valido = false;
        }
        if (jComboBoxCategoría.getSelectedIndex() == 0) {
            errores += "\nDebe seleccionar una categoría";
            valido = false;
        }
        if (jComboBoxCondicion.getSelectedIndex() == 0) {
            errores += "\nDebe seleccionar una condicion";
            valido = false;
        }
        if(urgente) {
            msgUrgente= "Se ha realizado un cargo de 5€ pora que este artículo destaque sobre los demás";
        
        }
        if (valido) {
            String idAlta = crearid();
            
            //guardar la imagen con un nombre igual al IDalta asignado al producto,
            //para posteriormente asociar la imagen la producto.
            try{
             bImage = ImageIO.read(seleccionado);
             ImageIO.write(bImage, "jpg", new File(".\\src\\IconosProductos\\"+idAlta+".jpg")); 
                
                
            }catch (IOException e) {
               System.out.println("Exception occured :" + e.getMessage());
            }
            Producto p = new Producto(idAlta, Usuarios.clienteActual, null, null, tituloAlta, descripcionAlta, categoriaAlta,
                    condicionAlta, 0, precioAlta, fechaAlta, Usuarios.clienteActual.getCiudad(), Usuarios.clienteActual.getCodigo_postal(), urgente);
            Tienda.tienda.add(p);
            Tienda.misproductos.add(p);
            Tienda.hashProdutos.put(p.getId(), p);
            System.out.print(Tienda.tienda);
                  
            JOptionPane.showMessageDialog(rootPane, "Producto dado de alta\n" + msgUrgente);
            this.dispose();
            Tienda.guardarTienda();            
            
        } else {

            JOptionPane.showMessageDialog(rootPane, errores);

        }

    }//GEN-LAST:event_jButtonVenderFinActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscarImagen;
    private javax.swing.JButton jButtonVenderFin;
    private javax.swing.JCheckBox jCheckBoxUrgente;
    private javax.swing.JComboBox<String> jComboBoxCategoría;
    private javax.swing.JComboBox<String> jComboBoxCondicion;
    private javax.swing.JFormattedTextField jFormattedPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JPanel jPanelImagenPre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextDescripcion;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    private String crearid() {

        String idAlta = UUID.randomUUID().toString();
        while (Tienda.hashProdutos.containsKey(idAlta)){
            
           idAlta = UUID.randomUUID().toString();
        
        }

        return idAlta;

    }
}
